### ISSUE TITLE
Password Dialogue Box Doesn't Appear

### ISSUE THREAD

**Issue by mottdm** [linuxmint/wayland#92] opened 2024-06-19 04:00 UTC
### Distribution

Mint 21.3 Edge

### Package version

6.0.4

### Graphics hardware in use

Nvidia Quadro P4000/Intel HD P630

### Frequency

Always

### Bug description

Issue with installing system packages or updates; I never get prompted to input my password in. No dialogue or prompts appear to input my password in. However, going through terminal with sudo apt update, install, etc works without issue

### Steps to reproduce

Attempt to install system package via software manager or install updates with update manager; no prompt for password appears. Updates and/or system packages refuse to install

### Expected behavior

Prompt for password should appear allowing password to be inputted to install updates or system packages the same way X11 does

### Additional information

Happens across other computers I have that use Linux Mint 21.3 Edge.

**Comment by rcalixte** [comment] 2024-06-19 04:25
Duplicate of #22

**Closed as not planned by rcalixte** 2024-06-19 04:25 UTC
Labels: bug
