### ISSUE TITLE
Cannot access Timeshift (EDIT: also problems with other actions that require entering a password, like Software Manager)

### ISSUE THREAD

**Issue by HalcyonDays2010s** [linuxmint/wayland#89] opened 2024-06-02 13:28 UTC
### Distribution

Mint 21.3

### Package version

Cinnamon 6.0.4

### Graphics hardware in use

Built in graphics of Intel Intel© Core™ i5-3570 CPU. (Mint System settings reports this as Intel Corporation Xeon E3-1200 v2/3rd Gen Core processor Graphics Controller)

### Frequency

Always

### Bug description

When pressing the TimeShift icon in the StartMenu, the TimeShift app doesn't open as it should. Though I do see something flashing really quick at the bottom left where my tray icons are, as if something gets minimised and then closed.

**EDIT:** I have just discovered that other actions that involve entering a password (like installing sotware through the Software Manager or creating a partition in Disks) all seem to be affected. So the issue is really with Authenticate and not specifically with TimeShift

### Steps to reproduce

- Log into Mint in Wayland mode
- Go to StartMenu and press the TimeShift icon in the list (or locate it with the search bar)

### Expected behavior

I should get the box where it asks for my password (like happens correctly in X11 mode), but I don't.

### Additional information

Scheduled TimeShift snapshots are still taken in Wayland mode, so TimeShift itself seems to work OK.

**Comment by haggen88** [comment] 2024-06-06 17:12
#22  related

**Comment by rcalixte** [comment] 2024-06-06 17:14
Duplicate of #22

**Closed as not planned by rcalixte** 2024-06-06 17:14 UTC
Labels: bug
