### ISSUE TITLE
Wayland use breaks Update Manager in 21.3 Mint release.

### ISSUE THREAD

**Issue by droj73** [linuxmint/wayland#60] opened 2024-01-30 20:33 UTC
### Distribution

Mint 21.3

### Package version

Cinnamon 6.0.4

### Graphics hardware in use

AMD Lucienne (ASUSTeK driver) amdgpu

### Frequency

Always

### Bug description

After selecting Wayland (Experimental) upon login, Update Manager no longer works.

### Steps to reproduce

1. Power on.
2. Select Wayland (Experimental) use.
3. Login.
4. Try to install update from Update Manager.

### Expected behavior

Update gets installed.

### Additional information

ASUS VivoBook laptop

**Comment by rcalixte** [comment] 2024-01-30 20:34
Duplicate of #22

**Closed as not planned by rcalixte** 2024-01-30 20:34 UTC
Labels: bug
