### ISSUE TITLE
There is no keyboard layout settings in Cinnamon on Wayland

### ISSUE THREAD

**Issue by Rizado** [linuxmint/wayland#41] opened 2024-01-13 16:57 UTC
### Distribution

Mint 21.3 Cinnamon

### Package version

6.0.4

### Graphics hardware in use

Intel UHD Graphic 630 (graphic core in CPU)

### Frequency

Always

### Bug description

When I open keyboard settong in Cinnamon with XServer there 3 tabs in window.
When I try to do in on Wayland there only 2 tabs - there is no tab with keyboard layout settings.

### Steps to reproduce

Run Linux Mint Cinnamon on Walland, then open keyboard settings.

### Expected behavior

Users must have capability for keyboard layout settings.

**Comment by rcalixte** [comment] 2024-01-13 17:00
Duplicate of #14

**Closed as not planned by rcalixte** 2024-01-13 17:00 UTC
Labels: bug
