### ISSUE TITLE
 Keyboard layouts not working

### ISSUE THREAD

**Issue by lucasgabmoreno** [linuxmint/wayland#112] opened 2024-11-16 15:19 UTC
### Distribution

Linux Mint 22

### Package version

Cinnamon 6.2.9

### Graphics hardware in use

NVIDIA GeForce GTX 1650 Mobile

### Frequency

Always

### Bug description

Can't set latin keyboard layout

X11:
![Captura de pantalla de 2024-11-16 12-04-01](https://github.com/user-attachments/assets/1540a25f-8a5f-4c6a-a24d-0a497f63f423)

Walyland:
![keyboard wayland](https://github.com/user-attachments/assets/ef299e29-3551-4d5d-9869-c4c04aa77156)

### Steps to reproduce

Run Keyboard app, then try to go to Layout Tab (doesn't exist) 

### Expected behavior

Layoutb Tab must exist

**Comment by rcalixte** [comment] 2024-11-16 15:20
Duplicate of #14

**Closed as not planned by rcalixte** 2024-11-16 15:20 UTC
Labels: bug
