### ISSUE TITLE
csd-keyboard in xwayland mode is missing layouts tab

### ISSUE THREAD

**Issue by wplapper** [linuxmint/wayland#16] opened 2023-12-10 19:31 UTC
When running linuxmint 21.3 beta in xwayland mode, the display is missing the "layouts" tab. See attached screenshot.
![linuxmint-21 3-beta-csd-keyboard](https://github.com/linuxmint/mint21.3-beta/assets/18740761/f82ea968-8abb-464d-bee5-f219748f95f5)

Bug happens “always”. Invoke it by using Menu -> System Settings Control Centre -> Keyboard.

In X11 mode, everything is fine.

I include the system repost from the machine: see 
[linuxmint-21.3-systemreport.txt](https://github.com/linuxmint/mint21.3-beta/files/13628952/linuxmint-21.3-systemreport.txt)
linuxmint-21.3-systemreport.txt

My keyboard is setxkbmap -print (X11)
xkb_keymap {
	xkb_keycodes  { include "evdev+aliases(qwerty)"	};
	xkb_types     { include "complete"	};
	xkb_compat    { include "complete"	};
	xkb_symbols   { include "pc+gb(extd)+inet(evdev)+group(win_space_toggle)+terminate(ctrl_alt_bksp)"	};
	xkb_geometry  { include "pc(pc105)"	};

But in Xwayland mode it is set to
xkb_keymap {
	xkb_keycodes  { include "evdev+aliases(qwerty)"	};
	xkb_types     { include "complete"	};
	xkb_compat    { include "complete"	};
	xkb_symbols   { include "pc+us+inet(evdev)"	};
	xkb_geometry  { include "pc(pc105)"	};
};

NOTE: keyboard is set to "us".

**Comment by mtwebster** [comment] 2023-12-10 22:54
Keyboard layouts aren't supported yet in wayland.

**Comment by stvoidit** [comment] 2024-01-11 20:58
Today I received an update to 21.3 from mintupdate.
There is a similar problem, there is no way to configure switching the keyboard layout.

**Comment by rcalixte** [comment] 2024-01-11 21:13
> Today I received an update to 21.3 from mintupdate. There is a similar problem, there is no way to configure switching the keyboard layout.

It still hasn't been implemented yet and it will not work until it has been implemented. As of today, there is no timeline for when this will happen.

**Comment by leigh123linux** [comment] 2024-02-01 13:43
Duplicate of #14

**Closed as completed by leigh123linux** 2024-02-01 13:43 UTC

**Comment by robekd** [comment] 2025-06-08 16:55
Fix this rofl
Za!ll are losing ppl that are used to qwertz lazouts.
