### ISSUE TITLE
Right clicking on thrid party applets show the menu very from from the applet icon

### ISSUE THREAD

**Issue by marmotte32** [linuxmint/wayland#27] opened 2023-12-15 18:52 UTC
### Distribution

Mint 21.3

### Package version

6.0.1

### Graphics hardware in use

Intel HD Graphics 4400 (HSW GT2) v: 4.6 Mesa 23.0.4-0ubuntu1~22.04.1

### Frequency

Always

### Bug description

Right clicking on thrid party applets show the menu very from from the applet icon
Please note that this does not happen with build in applet like network mgr wifi, battery icon, date calendar, sound volume.

![Capture d’écran du 2023-12-15 19-47-46](https://github.com/linuxmint/wayland/assets/4152464/cda448e6-0f88-443e-8eb4-b0573a6ea82c)

### Steps to reproduce

just right click on a third party applet like flameshot ...

### Expected behavior

the menu should be shown just above the icon
![Capture d’écran du 2023-12-15 19-46-35](https://github.com/linuxmint/wayland/assets/4152464/7262ef14-c6e7-4f27-aca1-d1d0572259f4)

**Comment by rcalixte** [comment] 2023-12-15 19:20
Duplicate of #21

**Closed as not planned by rcalixte** 2023-12-15 19:20 UTC
Labels: bug
