### ISSUE TITLE
workspace selection screen doesnt show desktop background in wayland

### ISSUE THREAD

**Issue by ENRORMA** [linuxmint/wayland#50] opened 2024-01-17 11:13 UTC
### Distribution

mint 21.3

### Package version

6.0.4

### Graphics hardware in use

AMD RX 590 and amdgpu driver

### Frequency

Always

### Bug description

in cinnamon Xorg the desktop background would be displayed in the workspace selection screen (crtl + alt + up)
the desktop background is not showing in wayland

# wayland
![wayland](https://github.com/linuxmint/wayland/assets/105936026/3b5863bc-cb6a-40cf-a2c3-46785d486b81)

# Xorg
![Xorg](https://github.com/linuxmint/wayland/assets/105936026/6ba6722b-a5d7-4524-9f27-0862e52be161)

### Steps to reproduce

launch cinnamon wayland
go into the workspace selector (crtl + alt + up)

### Expected behavior

dekstop background should be shown

**Comment by rcalixte** [comment] 2024-01-17 18:17
Duplicate of #12

**Closed as not planned by rcalixte** 2024-01-17 18:17 UTC
Labels: bug
