### ISSUE TITLE
GDebi error polkit-gnome-au

### ISSUE THREAD

**Issue by elduglas** [linuxmint/wayland#77] opened 2024-03-25 03:19 UTC
### Distribution

Mint 21.3

### Package version

6.0.4

### Frequency

Always

### Bug description

===================================================================
 Info                                                              
===================================================================
           PID: 2347 (polkit-gnome-au)
           UID: 1000 (ada)
           GID: 1000 (ada)
        Signal: 11 (SEGV)
     Timestamp: Sun 2024-03-24 20:00:19 -05 (1h 57min ago)
  Command Line: /usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1
    Executable: /usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1
 Control Group: /user.slice/user-1000.slice/session-c4.scope
          Unit: session-c4.scope
         Slice: user-1000.slice
       Session: c4
     Owner UID: 1000 (ada)
       Boot ID: fe1072b839c54030b1dd3f994aefb5a3
    Machine ID: 212c6e7485fc4dfe8004bd70f191827e
      Hostname: ada-lm
       Storage: /var/lib/systemd/coredump/core.polkit-gnome-au.1000.fe1072b839c54030b1dd3f994aefb5a3.2347.1711328419000000.zst (present)
     Disk Size: 1.8M
       Message: Process 2347 (polkit-gnome-au) of user 1000 dumped core.
                
                Found module linux-vdso.so.1 with build-id: 2bee596cf278856fcc3f881f16f86d158e171fba
                Found module im-wayland.so with build-id: c4609a1abc688e36f32c0b372a818c26e4c99f57
                Found module libgvfscommon.so with build-id: e7fa580fb91bb21aac9fc69229e0961dc743f2b1
                Found module libgvfsdbus.so with build-id: 28abe694dac468552cc1d23d6f643e7989de85e8
                Found module libdconfsettings.so with build-id: 28be9445dc37a4f123f206cda2ffc7dea558a315
                Found module libgcc_s.so.1 with build-id: e3a44e0da9c6e835d293ed8fd2882b4c4a87130c
                Found module libstdc++.so.6 with build-id: e37fe1a879783838de78cbc8c80621fa685d58a2
                Found module libicudata.so.70 with build-id: b1c2496dd0543023c7a19c961bb7f3abc818f465
                Found module libicuuc.so.70 with build-id: bef3ff1d70aadd68aab07d858a759360c8b919ae
                Found module libxkbfile.so.1 with build-id: b585f533dd10bd8c043f887705d4e45828baf206
                Found module libxml2.so.2 with build-id: aebf8e42966c3ce475ff9d9d51a762831adcbb61
                Found module libxklavier.so.16 with build-id: a581072418d786fb4a1d160ee7143bbd977025e7
                Found module libgnomekbd.so.8 with build-id: 636c4ae86d1bff2aa2cb92b39b42e41ff714ec7c
                Found module libgnomekbdui.so.8 with build-id: e01ea8bdf45e3995a2449f1cb4bd8e6bd886efa5
                Found module libxapp.so.1 with build-id: 2edf20e3d0050c0e5e1d27af3fee61b11ae84f5e
                Found module libxapp-gtk3-module.so with build-id: 42e91d0b54421ed6a3ef8be0b9060c76207dd4e2
                Found module libmd.so.0 with build-id: cd2d2f71b3967ebde30e2aa43b8eb63339020c06
                Found module libbrotlicommon.so.1 with build-id: 43a72967cf84155914c8b3e915926733d1e57c11
                Found module libbsd.so.0 with build-id: 9a6c72469251e2feb63e175ef5cb944ce6e00df3
                Found module libgpg-error.so.0 with build-id: 3fbec71c67bee60d8aef00697ee187079b0fb307
                Found module libdatrie.so.1 with build-id: 128b6874a47f2b783d9e9060d3caaee4110bfd3d
                Found module libbrotlidec.so.1 with build-id: 4b1f390dd6e24d49684db8b2443d082379e8e977
                Found module libXdmcp.so.6 with build-id: 6b60f99504aa1d3999ea02a14366d1a39d6c5dcf
                Found module libXau.so.6 with build-id: 7089b383cacbfc1760634a3be19a923e51fe3315
                Found module libpcre2-8.so.0 with build-id: 184a841c55fb7fe5e3873fcda8368c71016cd54c
                Found module libblkid.so.1 with build-id: cdf95a964e3302bb356fefc4b801fae8c4340b31
                Found module libgcrypt.so.20 with build-id: 60a5e524de0ed8323edf33e9eb9127a9eee02359
                Found module libcap.so.2 with build-id: b4bf900abf14aabe12d90988ceb30888acb2bcb0
                Found module liblz4.so.1 with build-id: a85971851cd059f1af80d553c8e7170d42ec59a1
                Found module libzstd.so.1 with build-id: 5d9d0d946a3154a748e87e17af9d14764519237b
                Found module liblzma.so.5 with build-id: b85da6c48eb60a646615392559483b93617ef265
                Found module libuuid.so.1 with build-id: 64c0d0cb22fa2bdeca075a0c0418ba5ff314b220
                Found module libexpat.so.1 with build-id: 488cca1472bb121a12e1c77bb58fe0a5c52f2aa9
                Found module libgraphite2.so.3 with build-id: 5ffbc76fc948f6b88d766a7210c2e6a329a6c278
                Found module libthai.so.0 with build-id: afa54530349e68380815d606d15dbfda8952799f
                Found module libatspi.so.0 with build-id: 2843c68233d5ba81da3d6bc31422e49472873dba
                Found module libdbus-1.so.3 with build-id: 63e8b99215502138cb63afd6d65851a5e837ed49
                Found module libXrender.so.1 with build-id: 7ccbfa4c24e93c42fa50dd2e42fa277630f9650c
                Found module libxcb-render.so.0 with build-id: cb521131fd3b0f2ee6056cbc2014b3b8ef0d5c0e
                Found module libxcb-shm.so.0 with build-id: edb24ef4079aa423edcc50a3bb0dfb912fe8a57a
                Found module libfreetype.so.6 with build-id: bc6c65a19e6f75fea5e74a7fd6c0b91182e1a8b0
                Found module libpixman-1.so.0 with build-id: 5e936cdac032b6048d9d1a8c0bb0e4a10c86d48c
                Found module libxcb.so.1 with build-id: 1bef862a339557aa16c34c7a4b27f8f3aea90517
                Found module ld-linux-x86-64.so.2 with build-id: 15921ea631d9f36502d20459c43e5c85b7d6ab76
                Found module libpcre.so.3 with build-id: 3982f316c887e3ad9598015fa5bae8557320476a
                Found module libffi.so.8 with build-id: 59c2a6b204f74f358ca7711d2dfd349d88711f6a
                Found module libselinux.so.1 with build-id: 6fa53202ce676297de24873c886443b2759bfd8a
                Found module libmount.so.1 with build-id: eeb33f2b4b9c3eb0a29575eb9932ef08663bd836
                Found module libz.so.1 with build-id: 30840b79ac329ecbf1dec0bb60180eed256d319f
                Found module libsystemd.so.0 with build-id: e17e357f3a8e8198b1de01bd084ca319c72d231b
                Found module libjpeg.so.8 with build-id: c54abff9294357e28532a76a049a4cb2542fc15b
                Found module libpng16.so.16 with build-id: d58bf7c11ac793d528926238d831792b5ef792cf
                Found module libXext.so.6 with build-id: 9fb1880e02dfa11a8c39cd1a170109de08302059
                Found module libwayland-client.so.0 with build-id: a85980f4efa33fa5cadfbf257349fef99d499427
                Found module libwayland-egl.so.1 with build-id: e13dfac5961e8fb58c54984fe8110a73c2f5ef99
                Found module libwayland-cursor.so.0 with build-id: abcd1ab467757354ac36fd0938b82d47d7aebe1f
                Found module libxkbcommon.so.0 with build-id: a4b17d939092101dc8f6b2a1d70eaf1fddb2dd51
                Found module libXdamage.so.1 with build-id: 8358b7625700dc247fa21fb4304cba877a28bb04
                Found module libXcomposite.so.1 with build-id: 2c84db5342304ba1a76db7dd9b7a3bfaa8a716ce
                Found module libXcursor.so.1 with build-id: d936a5db46d8babb0f2cc490df36b6b18a16d8aa
                Found module libXrandr.so.2 with build-id: 069f930a2b41f3908a1a92b1a51c38bd13a559e2
                Found module libXinerama.so.1 with build-id: 9823bebfa26a681265db4aeb09abf44deec38401
                Found module libfontconfig.so.1 with build-id: 0bb435fdd5ec37178e14ea03bb36f779a4b72a94
                Found module libharfbuzz.so.0 with build-id: 3b9c495c079286b8d1f55d0937a0a771593eb7e6
                Found module libpango-1.0.so.0 with build-id: 42c8896c53d9d22dc73ba7a78b326d61f34e4442
                Found module libpangoft2-1.0.so.0 with build-id: fc7f13d8298f5e10fb1acbaa5472ec8b6fbf2bd9
                Found module libm.so.6 with build-id: a88ef0199bd5e742ebd0c359edf5cb2be0ec08b5
                Found module libfribidi.so.0 with build-id: 6e075a666e1da8ffdb948d734e75d82b1b6dc0fb
                Found module libepoxy.so.0 with build-id: 5ea53a2b100e4b044eee19d5222881a724abf046
                Found module libatk-bridge-2.0.so.0 with build-id: 7e8009077fbdcd7bf094c51bf78742b96f216d73
                Found module libatk-1.0.so.0 with build-id: b93088667fbd06f6b72d273403d352e7c0554698
                Found module libcairo.so.2 with build-id: 60a39c3684e41370bd0a59ed1ecbdccf47e30069
                Found module libcairo-gobject.so.2 with build-id: 71b5bd37d77ea1862d2ed00e9f6ead482f307db8
                Found module libXfixes.so.3 with build-id: a9c550a40b8154a3b4b5e2ac182bb50c013c3f18
                Found module libXi.so.6 with build-id: 8ff5a3ac871a90fd9d0a7917c61f748a41c6b5ee
                Found module libX11.so.6 with build-id: 37a5d7bbb78e3a99ea8376a7c80ea0c62fe06494
                Found module libpangocairo-1.0.so.0 with build-id: 65987e60b791e0eb6231575b8d5cfd33a6379b22
                Found module libgmodule-2.0.so.0 with build-id: 8b369a368c3070d179ddf64724ffc229c3f214b5
                Found module libc.so.6 with build-id: c289da5071a3399de893d2af81d6a30c62646e1e
                Found module libglib-2.0.so.0 with build-id: c74e800dfd5f72649d673b44292f4a817e45150b
                Found module libgobject-2.0.so.0 with build-id: 7c47809b4e688382aab4127a2e07496450c5e6b0
                Found module libgio-2.0.so.0 with build-id: 07bd46a1bb58e321e6aabc67135d054e6b78069d
                Found module libpolkit-gobject-1.so.0 with build-id: a5c9ffbd93ee5ce4d2822f14f44af5175f8f7557
                Found module libpolkit-agent-1.so.0 with build-id: 8119ec1e8d33c79dd0c29c59b79e157b95f4e89f
                Found module libgdk_pixbuf-2.0.so.0 with build-id: 374b383e3b68b5d8b552519094129f401596e502
                Found module libgdk-3.so.0 with build-id: 97b768ef80858a79741be2492754d948989e63c6
                Found module libgtk-3.so.0 with build-id: 9a340345f5e200f42140f3cb4bacb407e91843f8
                Found module polkit-gnome-authentication-agent-1 with build-id: 3ecce1c8c6d621f96afc41998ea6ed81c352ea14
                Stack trace of thread 2347:
                #0  0x0000000000000000 n/a (n/a + 0x0)
===================================================================
 GDB Log                                                           
===================================================================

warning: Can't open file /memfd:wayland-cursor (deleted) during file-backed mapping note processing

warning: Can't open file /home/ada/.config/dconf/user (deleted) during file-backed mapping note processing

warning: Can't open file /run/user/1000/dconf/user (deleted) during file-backed mapping note processing
[New LWP 2347]
[New LWP 2360]
[New LWP 2354]
[New LWP 2357]
[New LWP 3421]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000000000000000 in ?? ()
[Current thread is 1 (Thread 0x7f2397770f00 (LWP 2347))]

===================================================================
 GDB Backtrace                                                     
===================================================================

warning: Can't open file /memfd:wayland-cursor (deleted) during file-backed mapping note processing

warning: Can't open file /home/ada/.config/dconf/user (deleted) during file-backed mapping note processing

warning: Can't open file /run/user/1000/dconf/user (deleted) during file-backed mapping note processing
[New LWP 2347]
[New LWP 2360]
[New LWP 2354]
[New LWP 2357]
[New LWP 3421]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000000000000000 in ?? ()
[Current thread is 1 (Thread 0x7f2397770f00 (LWP 2347))]
#0  0x0000000000000000 in ?? ()
#1  0x00007f2398a7819a in g_hash_table_lookup () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f2398e89438 in gdk_x11_atom_to_xatom_for_display () from /lib/x86_64-linux-gnu/libgdk-3.so.0
#3  0x00007f2398e90423 in gdk_x11_get_server_time () from /lib/x86_64-linux-gnu/libgdk-3.so.0
#4  0x000055d8140f834c in ?? ()
#5  0x00007f2398b8dd2f in g_closure_invoke () from /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#6  0x00007f2398ba9c36 in ?? () from /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#7  0x00007f2398bab614 in g_signal_emit_valist () from /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#8  0x00007f2398baba8e in g_signal_emit_by_name () from /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#9  0x00007f2398dda49e in ?? () from /lib/x86_64-linux-gnu/libpolkit-agent-1.so.0
#10 0x00007f2398a94c44 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#11 0x00007f2398aea258 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#12 0x00007f2398a942b3 in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#13 0x000055d8140f7f06 in ?? ()
#14 0x00007f2398a94c44 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#15 0x00007f2398aea258 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#16 0x00007f2398a942b3 in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#17 0x000055d8140f6d02 in ?? ()
#18 0x00007f239883fd90 in __libc_start_call_main (main=main@entry=0x55d8140f69f0, argc=argc@entry=1, argv=argv@entry=0x7ffc72ebdfb8) at ../sysdeps/nptl/libc_start_call_main.h:58
#19 0x00007f239883fe40 in __libc_start_main_impl (main=0x55d8140f69f0, argc=1, argv=0x7ffc72ebdfb8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffc72ebdfa8) at ../csu/libc-start.c:392
#20 0x000055d8140f6df5 in ?? ()

===================================================================
 GDB Backtrace (all threads)                                       
===================================================================

warning: Can't open file /memfd:wayland-cursor (deleted) during file-backed mapping note processing

warning: Can't open file /home/ada/.config/dconf/user (deleted) during file-backed mapping note processing

warning: Can't open file /run/user/1000/dconf/user (deleted) during file-backed mapping note processing
[New LWP 2347]
[New LWP 2360]
[New LWP 2354]
[New LWP 2357]
[New LWP 3421]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000000000000000 in ?? ()
[Current thread is 1 (Thread 0x7f2397770f00 (LWP 2347))]

Thread 5 (Thread 0x7f2391d34640 (LWP 3421)):
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
No locals.
#1  0x00007f2398ae404c in g_cond_wait_until () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007f2398a643e1 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007f2398ac680a in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#4  0x00007f2398ac3a51 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#5  0x00007f23988aaac3 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
        ret = <optimized out>
        pd = <optimized out>
        out = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140722236542208, 7629121171970937608, 139790747125312, 0, 139790859806672, 140722236542560, -7518980654659448056, -7519001068164918520}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#6  0x00007f239893c850 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
No locals.

Thread 4 (Thread 0x7f2393c32640 (LWP 2357)):
#0  0x00007f239892ebcf in __GI___poll (fds=0x55d8142c6460, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
        sc_ret = -516
        sc_cancel_oldtype = 0
        sc_ret = <optimized out>
#1  0x00007f2398aea1f6 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007f2398a923e3 in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007f2396f7933d in ?? () from /usr/lib/x86_64-linux-gnu/gio/modules/libdconfsettings.so
No symbol table info available.
#4  0x00007f2398ac3a51 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#5  0x00007f23988aaac3 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
        ret = <optimized out>
        pd = <optimized out>
        out = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140722236544064, 7629121171970937608, 139790779622976, 17, 139790859806672, 140722236544416, -7518985189071170808, -7519001068164918520}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#6  0x00007f239893c850 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
No locals.

Thread 3 (Thread 0x7f2394c82640 (LWP 2354)):
#0  0x00007f239892ebcf in __GI___poll (fds=0x55d8142ae330, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
        sc_ret = -516
        sc_cancel_oldtype = 0
        sc_ret = <optimized out>
#1  0x00007f2398aea1f6 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007f2398a923e3 in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007f2398a92431 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#4  0x00007f2398ac3a51 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#5  0x00007f23988aaac3 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
        ret = <optimized out>
        pd = <optimized out>
        out = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140722236544848, 7629121171970937608, 139790796727872, 2, 139790859806672, 140722236545200, -7518974151005220088, -7519001068164918520}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#6  0x00007f239893c850 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
No locals.

Thread 2 (Thread 0x7f2393431640 (LWP 2360)):
#0  0x00007f239892ebcf in __GI___poll (fds=0x7f238400ee60, nfds=3, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
        sc_ret = -516
        sc_cancel_oldtype = 0
        sc_ret = <optimized out>
#1  0x00007f2398aea1f6 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007f2398a942b3 in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007f2398cee07a in ?? () from /lib/x86_64-linux-gnu/libgio-2.0.so.0
No symbol table info available.
#4  0x00007f2398ac3a51 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#5  0x00007f23988aaac3 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
        ret = <optimized out>
        pd = <optimized out>
        out = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {139790788331088, 7629121171970937608, 139790771230272, 11, 139790859806672, 139790788331440, -7518984089022672120, -7519001068164918520}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#6  0x00007f239893c850 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
No locals.

Thread 1 (Thread 0x7f2397770f00 (LWP 2347)):
#0  0x0000000000000000 in ?? ()
No symbol table info available.
#1  0x00007f2398a7819a in g_hash_table_lookup () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007f2398e89438 in gdk_x11_atom_to_xatom_for_display () from /lib/x86_64-linux-gnu/libgdk-3.so.0
No symbol table info available.
#3  0x00007f2398e90423 in gdk_x11_get_server_time () from /lib/x86_64-linux-gnu/libgdk-3.so.0
No symbol table info available.
#4  0x000055d8140f834c in ?? ()
No symbol table info available.
#5  0x00007f2398b8dd2f in g_closure_invoke () from /lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
#6  0x00007f2398ba9c36 in ?? () from /lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
#7  0x00007f2398bab614 in g_signal_emit_valist () from /lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
#8  0x00007f2398baba8e in g_signal_emit_by_name () from /lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
#9  0x00007f2398dda49e in ?? () from /lib/x86_64-linux-gnu/libpolkit-agent-1.so.0
No symbol table info available.
#10 0x00007f2398a94c44 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#11 0x00007f2398aea258 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#12 0x00007f2398a942b3 in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#13 0x000055d8140f7f06 in ?? ()
No symbol table info available.
#14 0x00007f2398a94c44 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#15 0x00007f2398aea258 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#16 0x00007f2398a942b3 in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#17 0x000055d8140f6d02 in ?? ()
No symbol table info available.
#18 0x00007f239883fd90 in __libc_start_call_main (main=main@entry=0x55d8140f69f0, argc=argc@entry=1, argv=argv@entry=0x7ffc72ebdfb8) at ../sysdeps/nptl/libc_start_call_main.h:58
        self = <optimized out>
        result = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {0, 7629121171971068680, 140722236547000, 94386537851376, 94386537879232, 139790875418688, -7631085001699929336, -7519001131130465528}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#19 0x00007f239883fe40 in __libc_start_main_impl (main=0x55d8140f69f0, argc=1, argv=0x7ffc72ebdfb8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffc72ebdfa8) at ../csu/libc-start.c:392
No locals.
#20 0x000055d8140f6df5 in ?? ()
No symbol table info available.
#0  0x0000000000000000 in ?? ()
#1  0x00007f2398a7819a in g_hash_table_lookup () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f2398e89438 in gdk_x11_atom_to_xatom_for_display () from /lib/x86_64-linux-gnu/libgdk-3.so.0
#3  0x00007f2398e90423 in gdk_x11_get_server_time () from /lib/x86_64-linux-gnu/libgdk-3.so.0
#4  0x000055d8140f834c in ?? ()
#5  0x00007f2398b8dd2f in g_closure_invoke () from /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#6  0x00007f2398ba9c36 in ?? () from /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#7  0x00007f2398bab614 in g_signal_emit_valist () from /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#8  0x00007f2398baba8e in g_signal_emit_by_name () from /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#9  0x00007f2398dda49e in ?? () from /lib/x86_64-linux-gnu/libpolkit-agent-1.so.0
#10 0x00007f2398a94c44 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#11 0x00007f2398aea258 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#12 0x00007f2398a942b3 in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#13 0x000055d8140f7f06 in ?? ()
#14 0x00007f2398a94c44 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#15 0x00007f2398aea258 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#16 0x00007f2398a942b3 in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#17 0x000055d8140f6d02 in ?? ()
#18 0x00007f239883fd90 in __libc_start_call_main (main=main@entry=0x55d8140f69f0, argc=argc@entry=1, argv=argv@entry=0x7ffc72ebdfb8) at ../sysdeps/nptl/libc_start_call_main.h:58
#19 0x00007f239883fe40 in __libc_start_main_impl (main=0x55d8140f69f0, argc=1, argv=0x7ffc72ebdfb8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffc72ebdfa8) at ../csu/libc-start.c:392
#20 0x000055d8140f6df5 in ?? ()

### Steps to reproduce

1. Download vscode.
2. Try to install with GDebi.
3. Check the system reports.

### Expected behavior

May the VSCode package install correctly with GDebi.

**Comment by rcalixte** [comment] 2024-03-25 12:14
Duplicate of #26

**Closed as not planned by rcalixte** 2024-03-25 12:14 UTC
Labels: bug
